### ISSUE TITLE
femtable.org is down

### ISSUE THREAD

**Issue by blechta** [hnarayanan/fe-table#47]
@alogg

At some time between [August 10](https://web.archive.org/web/20200810072748/http://femtable.org/) and [September 30](https://web.archive.org/web/20200930052152/http://femtable.org/), the domain has expired. Any plans to resurrect it?

**Comment by blechta** [comment]
Ok, there's a replacement at http://z.umn.edu/femtable

**Comment by dnarnold** [comment]
Glad you found the replacement site.  It seems that even getting a redirect
from the old domain name would cost an annual fee, so we didn't do it.

**Comment by blechta** [comment]
Now I see [the problem](https://en.wikipedia.org/wiki/.org#Cost_of_registration)...
